//
// Type_Icon.cs.cs
//
// This file was generated by XMLSpy 2005 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using System.Collections;
using System.Xml;
using Altova.Types;

namespace LayerSet
{
	public class Type_Icon : Altova.Xml.Node
	{
		#region Forward constructors
		public Type_Icon() : base() { SetCollectionParents(); }
		public Type_Icon(XmlDocument doc) : base(doc) { SetCollectionParents(); }
		public Type_Icon(XmlNode node) : base(node) { SetCollectionParents(); }
		public Type_Icon(Altova.Xml.Node node) : base(node) { SetCollectionParents(); }
		#endregion // Forward constructors

		public override void AdjustPrefix()
		{

			for (int i = 0; i < DomChildCount(NodeType.Attribute, "", "ShowAtStartup"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Attribute, "", "ShowAtStartup", i);
				InternalAdjustPrefix(DOMNode, false);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "Name"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "Name", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "Latitude"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "Latitude", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_LatitudeCoordinate2(DOMNode).AdjustPrefix();
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "Longitude"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "Longitude", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_LongitudeCoordinate2(DOMNode).AdjustPrefix();
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "DistanceAboveSurface"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "DistanceAboveSurface", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "MinimumDisplayAltitude"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "MinimumDisplayAltitude", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "MaximumDisplayAltitude"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "MaximumDisplayAltitude", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "TextureFilePath"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "TextureFilePath", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "TextureWidthPixels"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "TextureWidthPixels", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "TextureHeightPixels"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "TextureHeightPixels", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "IconWidthPixels"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "IconWidthPixels", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "IconHeightPixels"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "IconHeightPixels", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "Caption"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "Caption", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_Caption(DOMNode).AdjustPrefix();
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "ClickableUrl"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "ClickableUrl", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "MouseoverTextColor"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "MouseoverTextColor", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_RGBColor2(DOMNode).AdjustPrefix();
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "ExtendedInformation"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "ExtendedInformation", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_ExtendedInformation(DOMNode).AdjustPrefix();
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "Description"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "Description", i);
				InternalAdjustPrefix(DOMNode, true);
			}
		}


		#region ShowAtStartup accessor methods
		public int GetShowAtStartupMinCount()
		{
			return 1;
		}

		public int ShowAtStartupMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowAtStartupMaxCount()
		{
			return 1;
		}

		public int ShowAtStartupMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowAtStartupCount()
		{
			return DomChildCount(NodeType.Attribute, "", "ShowAtStartup");
		}

		public int ShowAtStartupCount
		{
			get
			{
				return DomChildCount(NodeType.Attribute, "", "ShowAtStartup");
			}
		}

		public bool HasShowAtStartup()
		{
			return HasDomChild(NodeType.Attribute, "", "ShowAtStartup");
		}

		public SchemaBoolean GetShowAtStartupAt(int index)
		{
			return new SchemaBoolean(GetDomNodeValue(GetDomChildAt(NodeType.Attribute, "", "ShowAtStartup", index)));
		}

		public XmlNode GetStartingShowAtStartupCursor()
		{
			return GetDomFirstChild( NodeType.Attribute, "", "ShowAtStartup" );
		}

		public XmlNode GetAdvancedShowAtStartupCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Attribute, "", "ShowAtStartup", curNode );
		}

		public SchemaBoolean GetShowAtStartupValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaBoolean( curNode.Value );
		}


		public SchemaBoolean GetShowAtStartup()
		{
			return GetShowAtStartupAt(0);
		}

		public SchemaBoolean ShowAtStartup
		{
			get
			{
				return GetShowAtStartupAt(0);
			}
		}

		public void RemoveShowAtStartupAt(int index)
		{
			RemoveDomChildAt(NodeType.Attribute, "", "ShowAtStartup", index);
		}

		public void RemoveShowAtStartup()
		{
			while (HasShowAtStartup())
				RemoveShowAtStartupAt(0);
		}

		public void AddShowAtStartup(SchemaBoolean newValue)
		{
			AppendDomChild(NodeType.Attribute, "", "ShowAtStartup", newValue.ToString());
		}

		public void InsertShowAtStartupAt(SchemaBoolean newValue, int index)
		{
			InsertDomChildAt(NodeType.Attribute, "", "ShowAtStartup", index, newValue.ToString());
		}

		public void ReplaceShowAtStartupAt(SchemaBoolean newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Attribute, "", "ShowAtStartup", index, newValue.ToString());
		}
		#endregion // ShowAtStartup accessor methods

		#region ShowAtStartup collection
        public ShowAtStartupCollection	MyShowAtStartups = new ShowAtStartupCollection( );

        public class ShowAtStartupCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public ShowAtStartupEnumerator GetEnumerator() 
			{
				return new ShowAtStartupEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class ShowAtStartupEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public ShowAtStartupEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.ShowAtStartupCount );
			}
			public SchemaBoolean  Current 
			{
				get 
				{
					return(parent.GetShowAtStartupAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // ShowAtStartup collection

		#region Name accessor methods
		public int GetNameMinCount()
		{
			return 1;
		}

		public int NameMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetNameMaxCount()
		{
			return 1;
		}

		public int NameMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetNameCount()
		{
			return DomChildCount(NodeType.Element, "", "Name");
		}

		public int NameCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "Name");
			}
		}

		public bool HasName()
		{
			return HasDomChild(NodeType.Element, "", "Name");
		}

		public SchemaString GetNameAt(int index)
		{
			return new SchemaString(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "Name", index)));
		}

		public XmlNode GetStartingNameCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "Name" );
		}

		public XmlNode GetAdvancedNameCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "Name", curNode );
		}

		public SchemaString GetNameValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaString( curNode.InnerText );
		}


		public SchemaString GetName()
		{
			return GetNameAt(0);
		}

		public SchemaString Name
		{
			get
			{
				return GetNameAt(0);
			}
		}

		public void RemoveNameAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "Name", index);
		}

		public void RemoveName()
		{
			while (HasName())
				RemoveNameAt(0);
		}

		public void AddName(SchemaString newValue)
		{
			AppendDomChild(NodeType.Element, "", "Name", newValue.ToString());
		}

		public void InsertNameAt(SchemaString newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "Name", index, newValue.ToString());
		}

		public void ReplaceNameAt(SchemaString newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "Name", index, newValue.ToString());
		}
		#endregion // Name accessor methods

		#region Name collection
        public NameCollection	MyNames = new NameCollection( );

        public class NameCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public NameEnumerator GetEnumerator() 
			{
				return new NameEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class NameEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public NameEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.NameCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(parent.GetNameAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // Name collection

		#region Latitude accessor methods
		public int GetLatitudeMinCount()
		{
			return 1;
		}

		public int LatitudeMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetLatitudeMaxCount()
		{
			return 1;
		}

		public int LatitudeMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetLatitudeCount()
		{
			return DomChildCount(NodeType.Element, "", "Latitude");
		}

		public int LatitudeCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "Latitude");
			}
		}

		public bool HasLatitude()
		{
			return HasDomChild(NodeType.Element, "", "Latitude");
		}

		public Type_LatitudeCoordinate2 GetLatitudeAt(int index)
		{
			return new Type_LatitudeCoordinate2(GetDomChildAt(NodeType.Element, "", "Latitude", index));
		}

		public XmlNode GetStartingLatitudeCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "Latitude" );
		}

		public XmlNode GetAdvancedLatitudeCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "Latitude", curNode );
		}

		public Type_LatitudeCoordinate2 GetLatitudeValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new Type_LatitudeCoordinate2( curNode );
		}


		public Type_LatitudeCoordinate2 GetLatitude()
		{
			return GetLatitudeAt(0);
		}

		public Type_LatitudeCoordinate2 Latitude
		{
			get
			{
				return GetLatitudeAt(0);
			}
		}

		public void RemoveLatitudeAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "Latitude", index);
		}

		public void RemoveLatitude()
		{
			while (HasLatitude())
				RemoveLatitudeAt(0);
		}

		public void AddLatitude(Type_LatitudeCoordinate2 newValue)
		{
			AppendDomElement("", "Latitude", newValue);
		}

		public void InsertLatitudeAt(Type_LatitudeCoordinate2 newValue, int index)
		{
			InsertDomElementAt("", "Latitude", index, newValue);
		}

		public void ReplaceLatitudeAt(Type_LatitudeCoordinate2 newValue, int index)
		{
			ReplaceDomElementAt("", "Latitude", index, newValue);
		}
		#endregion // Latitude accessor methods

		#region Latitude collection
        public LatitudeCollection	MyLatitudes = new LatitudeCollection( );

        public class LatitudeCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public LatitudeEnumerator GetEnumerator() 
			{
				return new LatitudeEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class LatitudeEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public LatitudeEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.LatitudeCount );
			}
			public Type_LatitudeCoordinate2  Current 
			{
				get 
				{
					return(parent.GetLatitudeAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // Latitude collection

		#region Longitude accessor methods
		public int GetLongitudeMinCount()
		{
			return 1;
		}

		public int LongitudeMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetLongitudeMaxCount()
		{
			return 1;
		}

		public int LongitudeMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetLongitudeCount()
		{
			return DomChildCount(NodeType.Element, "", "Longitude");
		}

		public int LongitudeCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "Longitude");
			}
		}

		public bool HasLongitude()
		{
			return HasDomChild(NodeType.Element, "", "Longitude");
		}

		public Type_LongitudeCoordinate2 GetLongitudeAt(int index)
		{
			return new Type_LongitudeCoordinate2(GetDomChildAt(NodeType.Element, "", "Longitude", index));
		}

		public XmlNode GetStartingLongitudeCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "Longitude" );
		}

		public XmlNode GetAdvancedLongitudeCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "Longitude", curNode );
		}

		public Type_LongitudeCoordinate2 GetLongitudeValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new Type_LongitudeCoordinate2( curNode );
		}


		public Type_LongitudeCoordinate2 GetLongitude()
		{
			return GetLongitudeAt(0);
		}

		public Type_LongitudeCoordinate2 Longitude
		{
			get
			{
				return GetLongitudeAt(0);
			}
		}

		public void RemoveLongitudeAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "Longitude", index);
		}

		public void RemoveLongitude()
		{
			while (HasLongitude())
				RemoveLongitudeAt(0);
		}

		public void AddLongitude(Type_LongitudeCoordinate2 newValue)
		{
			AppendDomElement("", "Longitude", newValue);
		}

		public void InsertLongitudeAt(Type_LongitudeCoordinate2 newValue, int index)
		{
			InsertDomElementAt("", "Longitude", index, newValue);
		}

		public void ReplaceLongitudeAt(Type_LongitudeCoordinate2 newValue, int index)
		{
			ReplaceDomElementAt("", "Longitude", index, newValue);
		}
		#endregion // Longitude accessor methods

		#region Longitude collection
        public LongitudeCollection	MyLongitudes = new LongitudeCollection( );

        public class LongitudeCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public LongitudeEnumerator GetEnumerator() 
			{
				return new LongitudeEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class LongitudeEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public LongitudeEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.LongitudeCount );
			}
			public Type_LongitudeCoordinate2  Current 
			{
				get 
				{
					return(parent.GetLongitudeAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // Longitude collection

		#region DistanceAboveSurface accessor methods
		public int GetDistanceAboveSurfaceMinCount()
		{
			return 1;
		}

		public int DistanceAboveSurfaceMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetDistanceAboveSurfaceMaxCount()
		{
			return 1;
		}

		public int DistanceAboveSurfaceMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetDistanceAboveSurfaceCount()
		{
			return DomChildCount(NodeType.Element, "", "DistanceAboveSurface");
		}

		public int DistanceAboveSurfaceCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "DistanceAboveSurface");
			}
		}

		public bool HasDistanceAboveSurface()
		{
			return HasDomChild(NodeType.Element, "", "DistanceAboveSurface");
		}

		public SchemaDecimal GetDistanceAboveSurfaceAt(int index)
		{
			return new SchemaDecimal(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "DistanceAboveSurface", index)));
		}

		public XmlNode GetStartingDistanceAboveSurfaceCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "DistanceAboveSurface" );
		}

		public XmlNode GetAdvancedDistanceAboveSurfaceCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "DistanceAboveSurface", curNode );
		}

		public SchemaDecimal GetDistanceAboveSurfaceValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaDecimal( curNode.InnerText );
		}


		public SchemaDecimal GetDistanceAboveSurface()
		{
			return GetDistanceAboveSurfaceAt(0);
		}

		public SchemaDecimal DistanceAboveSurface
		{
			get
			{
				return GetDistanceAboveSurfaceAt(0);
			}
		}

		public void RemoveDistanceAboveSurfaceAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "DistanceAboveSurface", index);
		}

		public void RemoveDistanceAboveSurface()
		{
			while (HasDistanceAboveSurface())
				RemoveDistanceAboveSurfaceAt(0);
		}

		public void AddDistanceAboveSurface(SchemaDecimal newValue)
		{
			AppendDomChild(NodeType.Element, "", "DistanceAboveSurface", newValue.ToString());
		}

		public void InsertDistanceAboveSurfaceAt(SchemaDecimal newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "DistanceAboveSurface", index, newValue.ToString());
		}

		public void ReplaceDistanceAboveSurfaceAt(SchemaDecimal newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "DistanceAboveSurface", index, newValue.ToString());
		}
		#endregion // DistanceAboveSurface accessor methods

		#region DistanceAboveSurface collection
        public DistanceAboveSurfaceCollection	MyDistanceAboveSurfaces = new DistanceAboveSurfaceCollection( );

        public class DistanceAboveSurfaceCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public DistanceAboveSurfaceEnumerator GetEnumerator() 
			{
				return new DistanceAboveSurfaceEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class DistanceAboveSurfaceEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public DistanceAboveSurfaceEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.DistanceAboveSurfaceCount );
			}
			public SchemaDecimal  Current 
			{
				get 
				{
					return(parent.GetDistanceAboveSurfaceAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // DistanceAboveSurface collection

		#region MinimumDisplayAltitude accessor methods
		public int GetMinimumDisplayAltitudeMinCount()
		{
			return 0;
		}

		public int MinimumDisplayAltitudeMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetMinimumDisplayAltitudeMaxCount()
		{
			return 1;
		}

		public int MinimumDisplayAltitudeMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMinimumDisplayAltitudeCount()
		{
			return DomChildCount(NodeType.Element, "", "MinimumDisplayAltitude");
		}

		public int MinimumDisplayAltitudeCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "MinimumDisplayAltitude");
			}
		}

		public bool HasMinimumDisplayAltitude()
		{
			return HasDomChild(NodeType.Element, "", "MinimumDisplayAltitude");
		}

		public SchemaDecimal GetMinimumDisplayAltitudeAt(int index)
		{
			return new SchemaDecimal(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "MinimumDisplayAltitude", index)));
		}

		public XmlNode GetStartingMinimumDisplayAltitudeCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "MinimumDisplayAltitude" );
		}

		public XmlNode GetAdvancedMinimumDisplayAltitudeCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "MinimumDisplayAltitude", curNode );
		}

		public SchemaDecimal GetMinimumDisplayAltitudeValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaDecimal( curNode.InnerText );
		}


		public SchemaDecimal GetMinimumDisplayAltitude()
		{
			return GetMinimumDisplayAltitudeAt(0);
		}

		public SchemaDecimal MinimumDisplayAltitude
		{
			get
			{
				return GetMinimumDisplayAltitudeAt(0);
			}
		}

		public void RemoveMinimumDisplayAltitudeAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "MinimumDisplayAltitude", index);
		}

		public void RemoveMinimumDisplayAltitude()
		{
			while (HasMinimumDisplayAltitude())
				RemoveMinimumDisplayAltitudeAt(0);
		}

		public void AddMinimumDisplayAltitude(SchemaDecimal newValue)
		{
			AppendDomChild(NodeType.Element, "", "MinimumDisplayAltitude", newValue.ToString());
		}

		public void InsertMinimumDisplayAltitudeAt(SchemaDecimal newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "MinimumDisplayAltitude", index, newValue.ToString());
		}

		public void ReplaceMinimumDisplayAltitudeAt(SchemaDecimal newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "MinimumDisplayAltitude", index, newValue.ToString());
		}
		#endregion // MinimumDisplayAltitude accessor methods

		#region MinimumDisplayAltitude collection
        public MinimumDisplayAltitudeCollection	MyMinimumDisplayAltitudes = new MinimumDisplayAltitudeCollection( );

        public class MinimumDisplayAltitudeCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public MinimumDisplayAltitudeEnumerator GetEnumerator() 
			{
				return new MinimumDisplayAltitudeEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class MinimumDisplayAltitudeEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public MinimumDisplayAltitudeEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.MinimumDisplayAltitudeCount );
			}
			public SchemaDecimal  Current 
			{
				get 
				{
					return(parent.GetMinimumDisplayAltitudeAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // MinimumDisplayAltitude collection

		#region MaximumDisplayAltitude accessor methods
		public int GetMaximumDisplayAltitudeMinCount()
		{
			return 0;
		}

		public int MaximumDisplayAltitudeMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetMaximumDisplayAltitudeMaxCount()
		{
			return 1;
		}

		public int MaximumDisplayAltitudeMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMaximumDisplayAltitudeCount()
		{
			return DomChildCount(NodeType.Element, "", "MaximumDisplayAltitude");
		}

		public int MaximumDisplayAltitudeCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "MaximumDisplayAltitude");
			}
		}

		public bool HasMaximumDisplayAltitude()
		{
			return HasDomChild(NodeType.Element, "", "MaximumDisplayAltitude");
		}

		public SchemaDecimal GetMaximumDisplayAltitudeAt(int index)
		{
			return new SchemaDecimal(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "MaximumDisplayAltitude", index)));
		}

		public XmlNode GetStartingMaximumDisplayAltitudeCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "MaximumDisplayAltitude" );
		}

		public XmlNode GetAdvancedMaximumDisplayAltitudeCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "MaximumDisplayAltitude", curNode );
		}

		public SchemaDecimal GetMaximumDisplayAltitudeValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaDecimal( curNode.InnerText );
		}


		public SchemaDecimal GetMaximumDisplayAltitude()
		{
			return GetMaximumDisplayAltitudeAt(0);
		}

		public SchemaDecimal MaximumDisplayAltitude
		{
			get
			{
				return GetMaximumDisplayAltitudeAt(0);
			}
		}

		public void RemoveMaximumDisplayAltitudeAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "MaximumDisplayAltitude", index);
		}

		public void RemoveMaximumDisplayAltitude()
		{
			while (HasMaximumDisplayAltitude())
				RemoveMaximumDisplayAltitudeAt(0);
		}

		public void AddMaximumDisplayAltitude(SchemaDecimal newValue)
		{
			AppendDomChild(NodeType.Element, "", "MaximumDisplayAltitude", newValue.ToString());
		}

		public void InsertMaximumDisplayAltitudeAt(SchemaDecimal newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "MaximumDisplayAltitude", index, newValue.ToString());
		}

		public void ReplaceMaximumDisplayAltitudeAt(SchemaDecimal newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "MaximumDisplayAltitude", index, newValue.ToString());
		}
		#endregion // MaximumDisplayAltitude accessor methods

		#region MaximumDisplayAltitude collection
        public MaximumDisplayAltitudeCollection	MyMaximumDisplayAltitudes = new MaximumDisplayAltitudeCollection( );

        public class MaximumDisplayAltitudeCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public MaximumDisplayAltitudeEnumerator GetEnumerator() 
			{
				return new MaximumDisplayAltitudeEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class MaximumDisplayAltitudeEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public MaximumDisplayAltitudeEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.MaximumDisplayAltitudeCount );
			}
			public SchemaDecimal  Current 
			{
				get 
				{
					return(parent.GetMaximumDisplayAltitudeAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // MaximumDisplayAltitude collection

		#region TextureFilePath accessor methods
		public int GetTextureFilePathMinCount()
		{
			return 1;
		}

		public int TextureFilePathMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetTextureFilePathMaxCount()
		{
			return 1;
		}

		public int TextureFilePathMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetTextureFilePathCount()
		{
			return DomChildCount(NodeType.Element, "", "TextureFilePath");
		}

		public int TextureFilePathCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "TextureFilePath");
			}
		}

		public bool HasTextureFilePath()
		{
			return HasDomChild(NodeType.Element, "", "TextureFilePath");
		}

		public SchemaString GetTextureFilePathAt(int index)
		{
			return new SchemaString(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "TextureFilePath", index)));
		}

		public XmlNode GetStartingTextureFilePathCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "TextureFilePath" );
		}

		public XmlNode GetAdvancedTextureFilePathCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "TextureFilePath", curNode );
		}

		public SchemaString GetTextureFilePathValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaString( curNode.InnerText );
		}


		public SchemaString GetTextureFilePath()
		{
			return GetTextureFilePathAt(0);
		}

		public SchemaString TextureFilePath
		{
			get
			{
				return GetTextureFilePathAt(0);
			}
		}

		public void RemoveTextureFilePathAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "TextureFilePath", index);
		}

		public void RemoveTextureFilePath()
		{
			while (HasTextureFilePath())
				RemoveTextureFilePathAt(0);
		}

		public void AddTextureFilePath(SchemaString newValue)
		{
			AppendDomChild(NodeType.Element, "", "TextureFilePath", newValue.ToString());
		}

		public void InsertTextureFilePathAt(SchemaString newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "TextureFilePath", index, newValue.ToString());
		}

		public void ReplaceTextureFilePathAt(SchemaString newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "TextureFilePath", index, newValue.ToString());
		}
		#endregion // TextureFilePath accessor methods

		#region TextureFilePath collection
        public TextureFilePathCollection	MyTextureFilePaths = new TextureFilePathCollection( );

        public class TextureFilePathCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public TextureFilePathEnumerator GetEnumerator() 
			{
				return new TextureFilePathEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class TextureFilePathEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public TextureFilePathEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.TextureFilePathCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(parent.GetTextureFilePathAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // TextureFilePath collection

		#region TextureWidthPixels accessor methods
		public int GetTextureWidthPixelsMinCount()
		{
			return 1;
		}

		public int TextureWidthPixelsMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetTextureWidthPixelsMaxCount()
		{
			return 1;
		}

		public int TextureWidthPixelsMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetTextureWidthPixelsCount()
		{
			return DomChildCount(NodeType.Element, "", "TextureWidthPixels");
		}

		public int TextureWidthPixelsCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "TextureWidthPixels");
			}
		}

		public bool HasTextureWidthPixels()
		{
			return HasDomChild(NodeType.Element, "", "TextureWidthPixels");
		}

		public SchemaInt GetTextureWidthPixelsAt(int index)
		{
			return new SchemaInt(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "TextureWidthPixels", index)));
		}

		public XmlNode GetStartingTextureWidthPixelsCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "TextureWidthPixels" );
		}

		public XmlNode GetAdvancedTextureWidthPixelsCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "TextureWidthPixels", curNode );
		}

		public SchemaInt GetTextureWidthPixelsValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaInt( curNode.InnerText );
		}


		public SchemaInt GetTextureWidthPixels()
		{
			return GetTextureWidthPixelsAt(0);
		}

		public SchemaInt TextureWidthPixels
		{
			get
			{
				return GetTextureWidthPixelsAt(0);
			}
		}

		public void RemoveTextureWidthPixelsAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "TextureWidthPixels", index);
		}

		public void RemoveTextureWidthPixels()
		{
			while (HasTextureWidthPixels())
				RemoveTextureWidthPixelsAt(0);
		}

		public void AddTextureWidthPixels(SchemaInt newValue)
		{
			AppendDomChild(NodeType.Element, "", "TextureWidthPixels", newValue.ToString());
		}

		public void InsertTextureWidthPixelsAt(SchemaInt newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "TextureWidthPixels", index, newValue.ToString());
		}

		public void ReplaceTextureWidthPixelsAt(SchemaInt newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "TextureWidthPixels", index, newValue.ToString());
		}
		#endregion // TextureWidthPixels accessor methods

		#region TextureWidthPixels collection
        public TextureWidthPixelsCollection	MyTextureWidthPixelss = new TextureWidthPixelsCollection( );

        public class TextureWidthPixelsCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public TextureWidthPixelsEnumerator GetEnumerator() 
			{
				return new TextureWidthPixelsEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class TextureWidthPixelsEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public TextureWidthPixelsEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.TextureWidthPixelsCount );
			}
			public SchemaInt  Current 
			{
				get 
				{
					return(parent.GetTextureWidthPixelsAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // TextureWidthPixels collection

		#region TextureHeightPixels accessor methods
		public int GetTextureHeightPixelsMinCount()
		{
			return 1;
		}

		public int TextureHeightPixelsMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetTextureHeightPixelsMaxCount()
		{
			return 1;
		}

		public int TextureHeightPixelsMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetTextureHeightPixelsCount()
		{
			return DomChildCount(NodeType.Element, "", "TextureHeightPixels");
		}

		public int TextureHeightPixelsCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "TextureHeightPixels");
			}
		}

		public bool HasTextureHeightPixels()
		{
			return HasDomChild(NodeType.Element, "", "TextureHeightPixels");
		}

		public SchemaInt GetTextureHeightPixelsAt(int index)
		{
			return new SchemaInt(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "TextureHeightPixels", index)));
		}

		public XmlNode GetStartingTextureHeightPixelsCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "TextureHeightPixels" );
		}

		public XmlNode GetAdvancedTextureHeightPixelsCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "TextureHeightPixels", curNode );
		}

		public SchemaInt GetTextureHeightPixelsValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaInt( curNode.InnerText );
		}


		public SchemaInt GetTextureHeightPixels()
		{
			return GetTextureHeightPixelsAt(0);
		}

		public SchemaInt TextureHeightPixels
		{
			get
			{
				return GetTextureHeightPixelsAt(0);
			}
		}

		public void RemoveTextureHeightPixelsAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "TextureHeightPixels", index);
		}

		public void RemoveTextureHeightPixels()
		{
			while (HasTextureHeightPixels())
				RemoveTextureHeightPixelsAt(0);
		}

		public void AddTextureHeightPixels(SchemaInt newValue)
		{
			AppendDomChild(NodeType.Element, "", "TextureHeightPixels", newValue.ToString());
		}

		public void InsertTextureHeightPixelsAt(SchemaInt newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "TextureHeightPixels", index, newValue.ToString());
		}

		public void ReplaceTextureHeightPixelsAt(SchemaInt newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "TextureHeightPixels", index, newValue.ToString());
		}
		#endregion // TextureHeightPixels accessor methods

		#region TextureHeightPixels collection
        public TextureHeightPixelsCollection	MyTextureHeightPixelss = new TextureHeightPixelsCollection( );

        public class TextureHeightPixelsCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public TextureHeightPixelsEnumerator GetEnumerator() 
			{
				return new TextureHeightPixelsEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class TextureHeightPixelsEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public TextureHeightPixelsEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.TextureHeightPixelsCount );
			}
			public SchemaInt  Current 
			{
				get 
				{
					return(parent.GetTextureHeightPixelsAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // TextureHeightPixels collection

		#region IconWidthPixels accessor methods
		public int GetIconWidthPixelsMinCount()
		{
			return 1;
		}

		public int IconWidthPixelsMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetIconWidthPixelsMaxCount()
		{
			return 1;
		}

		public int IconWidthPixelsMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetIconWidthPixelsCount()
		{
			return DomChildCount(NodeType.Element, "", "IconWidthPixels");
		}

		public int IconWidthPixelsCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "IconWidthPixels");
			}
		}

		public bool HasIconWidthPixels()
		{
			return HasDomChild(NodeType.Element, "", "IconWidthPixels");
		}

		public SchemaInt GetIconWidthPixelsAt(int index)
		{
			return new SchemaInt(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "IconWidthPixels", index)));
		}

		public XmlNode GetStartingIconWidthPixelsCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "IconWidthPixels" );
		}

		public XmlNode GetAdvancedIconWidthPixelsCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "IconWidthPixels", curNode );
		}

		public SchemaInt GetIconWidthPixelsValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaInt( curNode.InnerText );
		}


		public SchemaInt GetIconWidthPixels()
		{
			return GetIconWidthPixelsAt(0);
		}

		public SchemaInt IconWidthPixels
		{
			get
			{
				return GetIconWidthPixelsAt(0);
			}
		}

		public void RemoveIconWidthPixelsAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "IconWidthPixels", index);
		}

		public void RemoveIconWidthPixels()
		{
			while (HasIconWidthPixels())
				RemoveIconWidthPixelsAt(0);
		}

		public void AddIconWidthPixels(SchemaInt newValue)
		{
			AppendDomChild(NodeType.Element, "", "IconWidthPixels", newValue.ToString());
		}

		public void InsertIconWidthPixelsAt(SchemaInt newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "IconWidthPixels", index, newValue.ToString());
		}

		public void ReplaceIconWidthPixelsAt(SchemaInt newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "IconWidthPixels", index, newValue.ToString());
		}
		#endregion // IconWidthPixels accessor methods

		#region IconWidthPixels collection
        public IconWidthPixelsCollection	MyIconWidthPixelss = new IconWidthPixelsCollection( );

        public class IconWidthPixelsCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public IconWidthPixelsEnumerator GetEnumerator() 
			{
				return new IconWidthPixelsEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class IconWidthPixelsEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public IconWidthPixelsEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.IconWidthPixelsCount );
			}
			public SchemaInt  Current 
			{
				get 
				{
					return(parent.GetIconWidthPixelsAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // IconWidthPixels collection

		#region IconHeightPixels accessor methods
		public int GetIconHeightPixelsMinCount()
		{
			return 1;
		}

		public int IconHeightPixelsMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetIconHeightPixelsMaxCount()
		{
			return 1;
		}

		public int IconHeightPixelsMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetIconHeightPixelsCount()
		{
			return DomChildCount(NodeType.Element, "", "IconHeightPixels");
		}

		public int IconHeightPixelsCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "IconHeightPixels");
			}
		}

		public bool HasIconHeightPixels()
		{
			return HasDomChild(NodeType.Element, "", "IconHeightPixels");
		}

		public SchemaInt GetIconHeightPixelsAt(int index)
		{
			return new SchemaInt(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "IconHeightPixels", index)));
		}

		public XmlNode GetStartingIconHeightPixelsCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "IconHeightPixels" );
		}

		public XmlNode GetAdvancedIconHeightPixelsCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "IconHeightPixels", curNode );
		}

		public SchemaInt GetIconHeightPixelsValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaInt( curNode.InnerText );
		}


		public SchemaInt GetIconHeightPixels()
		{
			return GetIconHeightPixelsAt(0);
		}

		public SchemaInt IconHeightPixels
		{
			get
			{
				return GetIconHeightPixelsAt(0);
			}
		}

		public void RemoveIconHeightPixelsAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "IconHeightPixels", index);
		}

		public void RemoveIconHeightPixels()
		{
			while (HasIconHeightPixels())
				RemoveIconHeightPixelsAt(0);
		}

		public void AddIconHeightPixels(SchemaInt newValue)
		{
			AppendDomChild(NodeType.Element, "", "IconHeightPixels", newValue.ToString());
		}

		public void InsertIconHeightPixelsAt(SchemaInt newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "IconHeightPixels", index, newValue.ToString());
		}

		public void ReplaceIconHeightPixelsAt(SchemaInt newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "IconHeightPixels", index, newValue.ToString());
		}
		#endregion // IconHeightPixels accessor methods

		#region IconHeightPixels collection
        public IconHeightPixelsCollection	MyIconHeightPixelss = new IconHeightPixelsCollection( );

        public class IconHeightPixelsCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public IconHeightPixelsEnumerator GetEnumerator() 
			{
				return new IconHeightPixelsEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class IconHeightPixelsEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public IconHeightPixelsEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.IconHeightPixelsCount );
			}
			public SchemaInt  Current 
			{
				get 
				{
					return(parent.GetIconHeightPixelsAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // IconHeightPixels collection

		#region Caption accessor methods
		public int GetCaptionMinCount()
		{
			return 0;
		}

		public int CaptionMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetCaptionMaxCount()
		{
			return 1;
		}

		public int CaptionMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetCaptionCount()
		{
			return DomChildCount(NodeType.Element, "", "Caption");
		}

		public int CaptionCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "Caption");
			}
		}

		public bool HasCaption()
		{
			return HasDomChild(NodeType.Element, "", "Caption");
		}

		public Type_Caption GetCaptionAt(int index)
		{
			return new Type_Caption(GetDomChildAt(NodeType.Element, "", "Caption", index));
		}

		public XmlNode GetStartingCaptionCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "Caption" );
		}

		public XmlNode GetAdvancedCaptionCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "Caption", curNode );
		}

		public Type_Caption GetCaptionValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new Type_Caption( curNode );
		}


		public Type_Caption GetCaption()
		{
			return GetCaptionAt(0);
		}

		public Type_Caption Caption
		{
			get
			{
				return GetCaptionAt(0);
			}
		}

		public void RemoveCaptionAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "Caption", index);
		}

		public void RemoveCaption()
		{
			while (HasCaption())
				RemoveCaptionAt(0);
		}

		public void AddCaption(Type_Caption newValue)
		{
			AppendDomElement("", "Caption", newValue);
		}

		public void InsertCaptionAt(Type_Caption newValue, int index)
		{
			InsertDomElementAt("", "Caption", index, newValue);
		}

		public void ReplaceCaptionAt(Type_Caption newValue, int index)
		{
			ReplaceDomElementAt("", "Caption", index, newValue);
		}
		#endregion // Caption accessor methods

		#region Caption collection
        public CaptionCollection	MyCaptions = new CaptionCollection( );

        public class CaptionCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public CaptionEnumerator GetEnumerator() 
			{
				return new CaptionEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class CaptionEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public CaptionEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.CaptionCount );
			}
			public Type_Caption  Current 
			{
				get 
				{
					return(parent.GetCaptionAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // Caption collection

		#region ClickableUrl accessor methods
		public int GetClickableUrlMinCount()
		{
			return 0;
		}

		public int ClickableUrlMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetClickableUrlMaxCount()
		{
			return 1;
		}

		public int ClickableUrlMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetClickableUrlCount()
		{
			return DomChildCount(NodeType.Element, "", "ClickableUrl");
		}

		public int ClickableUrlCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "ClickableUrl");
			}
		}

		public bool HasClickableUrl()
		{
			return HasDomChild(NodeType.Element, "", "ClickableUrl");
		}

		public SchemaString GetClickableUrlAt(int index)
		{
			return new SchemaString(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "ClickableUrl", index)));
		}

		public XmlNode GetStartingClickableUrlCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "ClickableUrl" );
		}

		public XmlNode GetAdvancedClickableUrlCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "ClickableUrl", curNode );
		}

		public SchemaString GetClickableUrlValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaString( curNode.InnerText );
		}


		public SchemaString GetClickableUrl()
		{
			return GetClickableUrlAt(0);
		}

		public SchemaString ClickableUrl
		{
			get
			{
				return GetClickableUrlAt(0);
			}
		}

		public void RemoveClickableUrlAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "ClickableUrl", index);
		}

		public void RemoveClickableUrl()
		{
			while (HasClickableUrl())
				RemoveClickableUrlAt(0);
		}

		public void AddClickableUrl(SchemaString newValue)
		{
			AppendDomChild(NodeType.Element, "", "ClickableUrl", newValue.ToString());
		}

		public void InsertClickableUrlAt(SchemaString newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "ClickableUrl", index, newValue.ToString());
		}

		public void ReplaceClickableUrlAt(SchemaString newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "ClickableUrl", index, newValue.ToString());
		}
		#endregion // ClickableUrl accessor methods

		#region ClickableUrl collection
        public ClickableUrlCollection	MyClickableUrls = new ClickableUrlCollection( );

        public class ClickableUrlCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public ClickableUrlEnumerator GetEnumerator() 
			{
				return new ClickableUrlEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class ClickableUrlEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public ClickableUrlEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.ClickableUrlCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(parent.GetClickableUrlAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // ClickableUrl collection

		#region MouseoverTextColor accessor methods
		public int GetMouseoverTextColorMinCount()
		{
			return 0;
		}

		public int MouseoverTextColorMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetMouseoverTextColorMaxCount()
		{
			return 1;
		}

		public int MouseoverTextColorMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMouseoverTextColorCount()
		{
			return DomChildCount(NodeType.Element, "", "MouseoverTextColor");
		}

		public int MouseoverTextColorCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "MouseoverTextColor");
			}
		}

		public bool HasMouseoverTextColor()
		{
			return HasDomChild(NodeType.Element, "", "MouseoverTextColor");
		}

		public Type_RGBColor2 GetMouseoverTextColorAt(int index)
		{
			return new Type_RGBColor2(GetDomChildAt(NodeType.Element, "", "MouseoverTextColor", index));
		}

		public XmlNode GetStartingMouseoverTextColorCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "MouseoverTextColor" );
		}

		public XmlNode GetAdvancedMouseoverTextColorCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "MouseoverTextColor", curNode );
		}

		public Type_RGBColor2 GetMouseoverTextColorValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new Type_RGBColor2( curNode );
		}


		public Type_RGBColor2 GetMouseoverTextColor()
		{
			return GetMouseoverTextColorAt(0);
		}

		public Type_RGBColor2 MouseoverTextColor
		{
			get
			{
				return GetMouseoverTextColorAt(0);
			}
		}

		public void RemoveMouseoverTextColorAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "MouseoverTextColor", index);
		}

		public void RemoveMouseoverTextColor()
		{
			while (HasMouseoverTextColor())
				RemoveMouseoverTextColorAt(0);
		}

		public void AddMouseoverTextColor(Type_RGBColor2 newValue)
		{
			AppendDomElement("", "MouseoverTextColor", newValue);
		}

		public void InsertMouseoverTextColorAt(Type_RGBColor2 newValue, int index)
		{
			InsertDomElementAt("", "MouseoverTextColor", index, newValue);
		}

		public void ReplaceMouseoverTextColorAt(Type_RGBColor2 newValue, int index)
		{
			ReplaceDomElementAt("", "MouseoverTextColor", index, newValue);
		}
		#endregion // MouseoverTextColor accessor methods

		#region MouseoverTextColor collection
        public MouseoverTextColorCollection	MyMouseoverTextColors = new MouseoverTextColorCollection( );

        public class MouseoverTextColorCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public MouseoverTextColorEnumerator GetEnumerator() 
			{
				return new MouseoverTextColorEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class MouseoverTextColorEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public MouseoverTextColorEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.MouseoverTextColorCount );
			}
			public Type_RGBColor2  Current 
			{
				get 
				{
					return(parent.GetMouseoverTextColorAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // MouseoverTextColor collection

		#region ExtendedInformation accessor methods
		public int GetExtendedInformationMinCount()
		{
			return 0;
		}

		public int ExtendedInformationMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetExtendedInformationMaxCount()
		{
			return 1;
		}

		public int ExtendedInformationMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetExtendedInformationCount()
		{
			return DomChildCount(NodeType.Element, "", "ExtendedInformation");
		}

		public int ExtendedInformationCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "ExtendedInformation");
			}
		}

		public bool HasExtendedInformation()
		{
			return HasDomChild(NodeType.Element, "", "ExtendedInformation");
		}

		public Type_ExtendedInformation GetExtendedInformationAt(int index)
		{
			return new Type_ExtendedInformation(GetDomChildAt(NodeType.Element, "", "ExtendedInformation", index));
		}

		public XmlNode GetStartingExtendedInformationCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "ExtendedInformation" );
		}

		public XmlNode GetAdvancedExtendedInformationCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "ExtendedInformation", curNode );
		}

		public Type_ExtendedInformation GetExtendedInformationValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new Type_ExtendedInformation( curNode );
		}


		public Type_ExtendedInformation GetExtendedInformation()
		{
			return GetExtendedInformationAt(0);
		}

		public Type_ExtendedInformation ExtendedInformation
		{
			get
			{
				return GetExtendedInformationAt(0);
			}
		}

		public void RemoveExtendedInformationAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "ExtendedInformation", index);
		}

		public void RemoveExtendedInformation()
		{
			while (HasExtendedInformation())
				RemoveExtendedInformationAt(0);
		}

		public void AddExtendedInformation(Type_ExtendedInformation newValue)
		{
			AppendDomElement("", "ExtendedInformation", newValue);
		}

		public void InsertExtendedInformationAt(Type_ExtendedInformation newValue, int index)
		{
			InsertDomElementAt("", "ExtendedInformation", index, newValue);
		}

		public void ReplaceExtendedInformationAt(Type_ExtendedInformation newValue, int index)
		{
			ReplaceDomElementAt("", "ExtendedInformation", index, newValue);
		}
		#endregion // ExtendedInformation accessor methods

		#region ExtendedInformation collection
        public ExtendedInformationCollection	MyExtendedInformations = new ExtendedInformationCollection( );

        public class ExtendedInformationCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public ExtendedInformationEnumerator GetEnumerator() 
			{
				return new ExtendedInformationEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class ExtendedInformationEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public ExtendedInformationEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.ExtendedInformationCount );
			}
			public Type_ExtendedInformation  Current 
			{
				get 
				{
					return(parent.GetExtendedInformationAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // ExtendedInformation collection

		#region Description accessor methods
		public int GetDescriptionMinCount()
		{
			return 0;
		}

		public int DescriptionMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetDescriptionMaxCount()
		{
			return 1;
		}

		public int DescriptionMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetDescriptionCount()
		{
			return DomChildCount(NodeType.Element, "", "Description");
		}

		public int DescriptionCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "Description");
			}
		}

		public bool HasDescription()
		{
			return HasDomChild(NodeType.Element, "", "Description");
		}

		public SchemaString GetDescriptionAt(int index)
		{
			return new SchemaString(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "Description", index)));
		}

		public XmlNode GetStartingDescriptionCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "Description" );
		}

		public XmlNode GetAdvancedDescriptionCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "Description", curNode );
		}

		public SchemaString GetDescriptionValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaString( curNode.InnerText );
		}


		public SchemaString GetDescription()
		{
			return GetDescriptionAt(0);
		}

		public SchemaString Description
		{
			get
			{
				return GetDescriptionAt(0);
			}
		}

		public void RemoveDescriptionAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "Description", index);
		}

		public void RemoveDescription()
		{
			while (HasDescription())
				RemoveDescriptionAt(0);
		}

		public void AddDescription(SchemaString newValue)
		{
			AppendDomChild(NodeType.Element, "", "Description", newValue.ToString());
		}

		public void InsertDescriptionAt(SchemaString newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "Description", index, newValue.ToString());
		}

		public void ReplaceDescriptionAt(SchemaString newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "Description", index, newValue.ToString());
		}
		#endregion // Description accessor methods

		#region Description collection
        public DescriptionCollection	MyDescriptions = new DescriptionCollection( );

        public class DescriptionCollection: IEnumerable
        {
            Type_Icon parent;
            public Type_Icon Parent
			{
				set
				{
					parent = value;
				}
			}
			public DescriptionEnumerator GetEnumerator() 
			{
				return new DescriptionEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class DescriptionEnumerator: IEnumerator 
        {
			int nIndex;
			Type_Icon parent;
			public DescriptionEnumerator(Type_Icon par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.DescriptionCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(parent.GetDescriptionAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // Description collection

        private void SetCollectionParents()
        {
            MyShowAtStartups.Parent = this; 
            MyNames.Parent = this; 
            MyLatitudes.Parent = this; 
            MyLongitudes.Parent = this; 
            MyDistanceAboveSurfaces.Parent = this; 
            MyMinimumDisplayAltitudes.Parent = this; 
            MyMaximumDisplayAltitudes.Parent = this; 
            MyTextureFilePaths.Parent = this; 
            MyTextureWidthPixelss.Parent = this; 
            MyTextureHeightPixelss.Parent = this; 
            MyIconWidthPixelss.Parent = this; 
            MyIconHeightPixelss.Parent = this; 
            MyCaptions.Parent = this; 
            MyClickableUrls.Parent = this; 
            MyMouseoverTextColors.Parent = this; 
            MyExtendedInformations.Parent = this; 
            MyDescriptions.Parent = this; 
	}
}
}
