//
// Type_ShapeFileLayer.cs.cs
//
// This file was generated by XMLSpy 2005 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using System.Collections;
using System.Xml;
using Altova.Types;

namespace LayerSet
{
	public class Type_ShapeFileLayer : Altova.Xml.Node
	{
		#region Forward constructors
		public Type_ShapeFileLayer() : base() { SetCollectionParents(); }
		public Type_ShapeFileLayer(XmlDocument doc) : base(doc) { SetCollectionParents(); }
		public Type_ShapeFileLayer(XmlNode node) : base(node) { SetCollectionParents(); }
		public Type_ShapeFileLayer(Altova.Xml.Node node) : base(node) { SetCollectionParents(); }
		#endregion // Forward constructors

		public override void AdjustPrefix()
		{

			for (int i = 0; i < DomChildCount(NodeType.Attribute, "", "ShowAtStartup"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Attribute, "", "ShowAtStartup", i);
				InternalAdjustPrefix(DOMNode, false);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "Name"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "Name", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "DistanceAboveSurface"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "DistanceAboveSurface", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "MasterFilePath"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "MasterFilePath", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "MinimumViewAltitude"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "MinimumViewAltitude", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "MaximumViewAltitude"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "MaximumViewAltitude", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "ShowPoints"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "ShowPoints", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "ShowBoundaries"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "ShowBoundaries", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "ShowFilledRegions"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "ShowFilledRegions", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "ScalarKey"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "ScalarKey", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "ShowScalarValues"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "ShowScalarValues", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "DisplayFont"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "DisplayFont", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_DisplayFont2(DOMNode).AdjustPrefix();
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "RGBColor"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "RGBColor", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_RGBColor2(DOMNode).AdjustPrefix();
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "WinColorName"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "WinColorName", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "ExtendedInformation"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "ExtendedInformation", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_ExtendedInformation(DOMNode).AdjustPrefix();
			}
		}


		#region ShowAtStartup accessor methods
		public int GetShowAtStartupMinCount()
		{
			return 1;
		}

		public int ShowAtStartupMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowAtStartupMaxCount()
		{
			return 1;
		}

		public int ShowAtStartupMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowAtStartupCount()
		{
			return DomChildCount(NodeType.Attribute, "", "ShowAtStartup");
		}

		public int ShowAtStartupCount
		{
			get
			{
				return DomChildCount(NodeType.Attribute, "", "ShowAtStartup");
			}
		}

		public bool HasShowAtStartup()
		{
			return HasDomChild(NodeType.Attribute, "", "ShowAtStartup");
		}

		public SchemaBoolean GetShowAtStartupAt(int index)
		{
			return new SchemaBoolean(GetDomNodeValue(GetDomChildAt(NodeType.Attribute, "", "ShowAtStartup", index)));
		}

		public XmlNode GetStartingShowAtStartupCursor()
		{
			return GetDomFirstChild( NodeType.Attribute, "", "ShowAtStartup" );
		}

		public XmlNode GetAdvancedShowAtStartupCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Attribute, "", "ShowAtStartup", curNode );
		}

		public SchemaBoolean GetShowAtStartupValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaBoolean( curNode.Value );
		}


		public SchemaBoolean GetShowAtStartup()
		{
			return GetShowAtStartupAt(0);
		}

		public SchemaBoolean ShowAtStartup
		{
			get
			{
				return GetShowAtStartupAt(0);
			}
		}

		public void RemoveShowAtStartupAt(int index)
		{
			RemoveDomChildAt(NodeType.Attribute, "", "ShowAtStartup", index);
		}

		public void RemoveShowAtStartup()
		{
			while (HasShowAtStartup())
				RemoveShowAtStartupAt(0);
		}

		public void AddShowAtStartup(SchemaBoolean newValue)
		{
			AppendDomChild(NodeType.Attribute, "", "ShowAtStartup", newValue.ToString());
		}

		public void InsertShowAtStartupAt(SchemaBoolean newValue, int index)
		{
			InsertDomChildAt(NodeType.Attribute, "", "ShowAtStartup", index, newValue.ToString());
		}

		public void ReplaceShowAtStartupAt(SchemaBoolean newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Attribute, "", "ShowAtStartup", index, newValue.ToString());
		}
		#endregion // ShowAtStartup accessor methods

		#region ShowAtStartup collection
        public ShowAtStartupCollection	MyShowAtStartups = new ShowAtStartupCollection( );

        public class ShowAtStartupCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public ShowAtStartupEnumerator GetEnumerator() 
			{
				return new ShowAtStartupEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class ShowAtStartupEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public ShowAtStartupEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.ShowAtStartupCount );
			}
			public SchemaBoolean  Current 
			{
				get 
				{
					return(parent.GetShowAtStartupAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // ShowAtStartup collection

		#region Name accessor methods
		public int GetNameMinCount()
		{
			return 1;
		}

		public int NameMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetNameMaxCount()
		{
			return 1;
		}

		public int NameMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetNameCount()
		{
			return DomChildCount(NodeType.Element, "", "Name");
		}

		public int NameCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "Name");
			}
		}

		public bool HasName()
		{
			return HasDomChild(NodeType.Element, "", "Name");
		}

		public SchemaString GetNameAt(int index)
		{
			return new SchemaString(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "Name", index)));
		}

		public XmlNode GetStartingNameCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "Name" );
		}

		public XmlNode GetAdvancedNameCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "Name", curNode );
		}

		public SchemaString GetNameValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaString( curNode.InnerText );
		}


		public SchemaString GetName()
		{
			return GetNameAt(0);
		}

		public SchemaString Name
		{
			get
			{
				return GetNameAt(0);
			}
		}

		public void RemoveNameAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "Name", index);
		}

		public void RemoveName()
		{
			while (HasName())
				RemoveNameAt(0);
		}

		public void AddName(SchemaString newValue)
		{
			AppendDomChild(NodeType.Element, "", "Name", newValue.ToString());
		}

		public void InsertNameAt(SchemaString newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "Name", index, newValue.ToString());
		}

		public void ReplaceNameAt(SchemaString newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "Name", index, newValue.ToString());
		}
		#endregion // Name accessor methods

		#region Name collection
        public NameCollection	MyNames = new NameCollection( );

        public class NameCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public NameEnumerator GetEnumerator() 
			{
				return new NameEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class NameEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public NameEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.NameCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(parent.GetNameAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // Name collection

		#region DistanceAboveSurface accessor methods
		public int GetDistanceAboveSurfaceMinCount()
		{
			return 1;
		}

		public int DistanceAboveSurfaceMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetDistanceAboveSurfaceMaxCount()
		{
			return 1;
		}

		public int DistanceAboveSurfaceMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetDistanceAboveSurfaceCount()
		{
			return DomChildCount(NodeType.Element, "", "DistanceAboveSurface");
		}

		public int DistanceAboveSurfaceCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "DistanceAboveSurface");
			}
		}

		public bool HasDistanceAboveSurface()
		{
			return HasDomChild(NodeType.Element, "", "DistanceAboveSurface");
		}

		public SchemaDecimal GetDistanceAboveSurfaceAt(int index)
		{
			return new SchemaDecimal(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "DistanceAboveSurface", index)));
		}

		public XmlNode GetStartingDistanceAboveSurfaceCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "DistanceAboveSurface" );
		}

		public XmlNode GetAdvancedDistanceAboveSurfaceCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "DistanceAboveSurface", curNode );
		}

		public SchemaDecimal GetDistanceAboveSurfaceValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaDecimal( curNode.InnerText );
		}


		public SchemaDecimal GetDistanceAboveSurface()
		{
			return GetDistanceAboveSurfaceAt(0);
		}

		public SchemaDecimal DistanceAboveSurface
		{
			get
			{
				return GetDistanceAboveSurfaceAt(0);
			}
		}

		public void RemoveDistanceAboveSurfaceAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "DistanceAboveSurface", index);
		}

		public void RemoveDistanceAboveSurface()
		{
			while (HasDistanceAboveSurface())
				RemoveDistanceAboveSurfaceAt(0);
		}

		public void AddDistanceAboveSurface(SchemaDecimal newValue)
		{
			AppendDomChild(NodeType.Element, "", "DistanceAboveSurface", newValue.ToString());
		}

		public void InsertDistanceAboveSurfaceAt(SchemaDecimal newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "DistanceAboveSurface", index, newValue.ToString());
		}

		public void ReplaceDistanceAboveSurfaceAt(SchemaDecimal newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "DistanceAboveSurface", index, newValue.ToString());
		}
		#endregion // DistanceAboveSurface accessor methods

		#region DistanceAboveSurface collection
        public DistanceAboveSurfaceCollection	MyDistanceAboveSurfaces = new DistanceAboveSurfaceCollection( );

        public class DistanceAboveSurfaceCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public DistanceAboveSurfaceEnumerator GetEnumerator() 
			{
				return new DistanceAboveSurfaceEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class DistanceAboveSurfaceEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public DistanceAboveSurfaceEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.DistanceAboveSurfaceCount );
			}
			public SchemaDecimal  Current 
			{
				get 
				{
					return(parent.GetDistanceAboveSurfaceAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // DistanceAboveSurface collection

		#region MasterFilePath accessor methods
		public int GetMasterFilePathMinCount()
		{
			return 1;
		}

		public int MasterFilePathMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMasterFilePathMaxCount()
		{
			return 1;
		}

		public int MasterFilePathMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMasterFilePathCount()
		{
			return DomChildCount(NodeType.Element, "", "MasterFilePath");
		}

		public int MasterFilePathCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "MasterFilePath");
			}
		}

		public bool HasMasterFilePath()
		{
			return HasDomChild(NodeType.Element, "", "MasterFilePath");
		}

		public SchemaString GetMasterFilePathAt(int index)
		{
			return new SchemaString(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "MasterFilePath", index)));
		}

		public XmlNode GetStartingMasterFilePathCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "MasterFilePath" );
		}

		public XmlNode GetAdvancedMasterFilePathCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "MasterFilePath", curNode );
		}

		public SchemaString GetMasterFilePathValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaString( curNode.InnerText );
		}


		public SchemaString GetMasterFilePath()
		{
			return GetMasterFilePathAt(0);
		}

		public SchemaString MasterFilePath
		{
			get
			{
				return GetMasterFilePathAt(0);
			}
		}

		public void RemoveMasterFilePathAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "MasterFilePath", index);
		}

		public void RemoveMasterFilePath()
		{
			while (HasMasterFilePath())
				RemoveMasterFilePathAt(0);
		}

		public void AddMasterFilePath(SchemaString newValue)
		{
			AppendDomChild(NodeType.Element, "", "MasterFilePath", newValue.ToString());
		}

		public void InsertMasterFilePathAt(SchemaString newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "MasterFilePath", index, newValue.ToString());
		}

		public void ReplaceMasterFilePathAt(SchemaString newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "MasterFilePath", index, newValue.ToString());
		}
		#endregion // MasterFilePath accessor methods

		#region MasterFilePath collection
        public MasterFilePathCollection	MyMasterFilePaths = new MasterFilePathCollection( );

        public class MasterFilePathCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public MasterFilePathEnumerator GetEnumerator() 
			{
				return new MasterFilePathEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class MasterFilePathEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public MasterFilePathEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.MasterFilePathCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(parent.GetMasterFilePathAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // MasterFilePath collection

		#region MinimumViewAltitude accessor methods
		public int GetMinimumViewAltitudeMinCount()
		{
			return 1;
		}

		public int MinimumViewAltitudeMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMinimumViewAltitudeMaxCount()
		{
			return 1;
		}

		public int MinimumViewAltitudeMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMinimumViewAltitudeCount()
		{
			return DomChildCount(NodeType.Element, "", "MinimumViewAltitude");
		}

		public int MinimumViewAltitudeCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "MinimumViewAltitude");
			}
		}

		public bool HasMinimumViewAltitude()
		{
			return HasDomChild(NodeType.Element, "", "MinimumViewAltitude");
		}

		public SchemaDecimal GetMinimumViewAltitudeAt(int index)
		{
			return new SchemaDecimal(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "MinimumViewAltitude", index)));
		}

		public XmlNode GetStartingMinimumViewAltitudeCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "MinimumViewAltitude" );
		}

		public XmlNode GetAdvancedMinimumViewAltitudeCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "MinimumViewAltitude", curNode );
		}

		public SchemaDecimal GetMinimumViewAltitudeValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaDecimal( curNode.InnerText );
		}


		public SchemaDecimal GetMinimumViewAltitude()
		{
			return GetMinimumViewAltitudeAt(0);
		}

		public SchemaDecimal MinimumViewAltitude
		{
			get
			{
				return GetMinimumViewAltitudeAt(0);
			}
		}

		public void RemoveMinimumViewAltitudeAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "MinimumViewAltitude", index);
		}

		public void RemoveMinimumViewAltitude()
		{
			while (HasMinimumViewAltitude())
				RemoveMinimumViewAltitudeAt(0);
		}

		public void AddMinimumViewAltitude(SchemaDecimal newValue)
		{
			AppendDomChild(NodeType.Element, "", "MinimumViewAltitude", newValue.ToString());
		}

		public void InsertMinimumViewAltitudeAt(SchemaDecimal newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "MinimumViewAltitude", index, newValue.ToString());
		}

		public void ReplaceMinimumViewAltitudeAt(SchemaDecimal newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "MinimumViewAltitude", index, newValue.ToString());
		}
		#endregion // MinimumViewAltitude accessor methods

		#region MinimumViewAltitude collection
        public MinimumViewAltitudeCollection	MyMinimumViewAltitudes = new MinimumViewAltitudeCollection( );

        public class MinimumViewAltitudeCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public MinimumViewAltitudeEnumerator GetEnumerator() 
			{
				return new MinimumViewAltitudeEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class MinimumViewAltitudeEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public MinimumViewAltitudeEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.MinimumViewAltitudeCount );
			}
			public SchemaDecimal  Current 
			{
				get 
				{
					return(parent.GetMinimumViewAltitudeAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // MinimumViewAltitude collection

		#region MaximumViewAltitude accessor methods
		public int GetMaximumViewAltitudeMinCount()
		{
			return 1;
		}

		public int MaximumViewAltitudeMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMaximumViewAltitudeMaxCount()
		{
			return 1;
		}

		public int MaximumViewAltitudeMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMaximumViewAltitudeCount()
		{
			return DomChildCount(NodeType.Element, "", "MaximumViewAltitude");
		}

		public int MaximumViewAltitudeCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "MaximumViewAltitude");
			}
		}

		public bool HasMaximumViewAltitude()
		{
			return HasDomChild(NodeType.Element, "", "MaximumViewAltitude");
		}

		public SchemaDecimal GetMaximumViewAltitudeAt(int index)
		{
			return new SchemaDecimal(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "MaximumViewAltitude", index)));
		}

		public XmlNode GetStartingMaximumViewAltitudeCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "MaximumViewAltitude" );
		}

		public XmlNode GetAdvancedMaximumViewAltitudeCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "MaximumViewAltitude", curNode );
		}

		public SchemaDecimal GetMaximumViewAltitudeValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaDecimal( curNode.InnerText );
		}


		public SchemaDecimal GetMaximumViewAltitude()
		{
			return GetMaximumViewAltitudeAt(0);
		}

		public SchemaDecimal MaximumViewAltitude
		{
			get
			{
				return GetMaximumViewAltitudeAt(0);
			}
		}

		public void RemoveMaximumViewAltitudeAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "MaximumViewAltitude", index);
		}

		public void RemoveMaximumViewAltitude()
		{
			while (HasMaximumViewAltitude())
				RemoveMaximumViewAltitudeAt(0);
		}

		public void AddMaximumViewAltitude(SchemaDecimal newValue)
		{
			AppendDomChild(NodeType.Element, "", "MaximumViewAltitude", newValue.ToString());
		}

		public void InsertMaximumViewAltitudeAt(SchemaDecimal newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "MaximumViewAltitude", index, newValue.ToString());
		}

		public void ReplaceMaximumViewAltitudeAt(SchemaDecimal newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "MaximumViewAltitude", index, newValue.ToString());
		}
		#endregion // MaximumViewAltitude accessor methods

		#region MaximumViewAltitude collection
        public MaximumViewAltitudeCollection	MyMaximumViewAltitudes = new MaximumViewAltitudeCollection( );

        public class MaximumViewAltitudeCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public MaximumViewAltitudeEnumerator GetEnumerator() 
			{
				return new MaximumViewAltitudeEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class MaximumViewAltitudeEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public MaximumViewAltitudeEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.MaximumViewAltitudeCount );
			}
			public SchemaDecimal  Current 
			{
				get 
				{
					return(parent.GetMaximumViewAltitudeAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // MaximumViewAltitude collection

		#region ShowPoints accessor methods
		public int GetShowPointsMinCount()
		{
			return 0;
		}

		public int ShowPointsMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetShowPointsMaxCount()
		{
			return 1;
		}

		public int ShowPointsMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowPointsCount()
		{
			return DomChildCount(NodeType.Element, "", "ShowPoints");
		}

		public int ShowPointsCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "ShowPoints");
			}
		}

		public bool HasShowPoints()
		{
			return HasDomChild(NodeType.Element, "", "ShowPoints");
		}

		public SchemaBoolean GetShowPointsAt(int index)
		{
			return new SchemaBoolean(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "ShowPoints", index)));
		}

		public XmlNode GetStartingShowPointsCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "ShowPoints" );
		}

		public XmlNode GetAdvancedShowPointsCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "ShowPoints", curNode );
		}

		public SchemaBoolean GetShowPointsValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaBoolean( curNode.InnerText );
		}


		public SchemaBoolean GetShowPoints()
		{
			return GetShowPointsAt(0);
		}

		public SchemaBoolean ShowPoints
		{
			get
			{
				return GetShowPointsAt(0);
			}
		}

		public void RemoveShowPointsAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "ShowPoints", index);
		}

		public void RemoveShowPoints()
		{
			while (HasShowPoints())
				RemoveShowPointsAt(0);
		}

		public void AddShowPoints(SchemaBoolean newValue)
		{
			AppendDomChild(NodeType.Element, "", "ShowPoints", newValue.ToString());
		}

		public void InsertShowPointsAt(SchemaBoolean newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "ShowPoints", index, newValue.ToString());
		}

		public void ReplaceShowPointsAt(SchemaBoolean newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "ShowPoints", index, newValue.ToString());
		}
		#endregion // ShowPoints accessor methods

		#region ShowPoints collection
        public ShowPointsCollection	MyShowPointss = new ShowPointsCollection( );

        public class ShowPointsCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public ShowPointsEnumerator GetEnumerator() 
			{
				return new ShowPointsEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class ShowPointsEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public ShowPointsEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.ShowPointsCount );
			}
			public SchemaBoolean  Current 
			{
				get 
				{
					return(parent.GetShowPointsAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // ShowPoints collection

		#region ShowBoundaries accessor methods
		public int GetShowBoundariesMinCount()
		{
			return 0;
		}

		public int ShowBoundariesMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetShowBoundariesMaxCount()
		{
			return 1;
		}

		public int ShowBoundariesMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowBoundariesCount()
		{
			return DomChildCount(NodeType.Element, "", "ShowBoundaries");
		}

		public int ShowBoundariesCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "ShowBoundaries");
			}
		}

		public bool HasShowBoundaries()
		{
			return HasDomChild(NodeType.Element, "", "ShowBoundaries");
		}

		public SchemaBoolean GetShowBoundariesAt(int index)
		{
			return new SchemaBoolean(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "ShowBoundaries", index)));
		}

		public XmlNode GetStartingShowBoundariesCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "ShowBoundaries" );
		}

		public XmlNode GetAdvancedShowBoundariesCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "ShowBoundaries", curNode );
		}

		public SchemaBoolean GetShowBoundariesValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaBoolean( curNode.InnerText );
		}


		public SchemaBoolean GetShowBoundaries()
		{
			return GetShowBoundariesAt(0);
		}

		public SchemaBoolean ShowBoundaries
		{
			get
			{
				return GetShowBoundariesAt(0);
			}
		}

		public void RemoveShowBoundariesAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "ShowBoundaries", index);
		}

		public void RemoveShowBoundaries()
		{
			while (HasShowBoundaries())
				RemoveShowBoundariesAt(0);
		}

		public void AddShowBoundaries(SchemaBoolean newValue)
		{
			AppendDomChild(NodeType.Element, "", "ShowBoundaries", newValue.ToString());
		}

		public void InsertShowBoundariesAt(SchemaBoolean newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "ShowBoundaries", index, newValue.ToString());
		}

		public void ReplaceShowBoundariesAt(SchemaBoolean newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "ShowBoundaries", index, newValue.ToString());
		}
		#endregion // ShowBoundaries accessor methods

		#region ShowBoundaries collection
        public ShowBoundariesCollection	MyShowBoundariess = new ShowBoundariesCollection( );

        public class ShowBoundariesCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public ShowBoundariesEnumerator GetEnumerator() 
			{
				return new ShowBoundariesEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class ShowBoundariesEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public ShowBoundariesEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.ShowBoundariesCount );
			}
			public SchemaBoolean  Current 
			{
				get 
				{
					return(parent.GetShowBoundariesAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // ShowBoundaries collection

		#region ShowFilledRegions accessor methods
		public int GetShowFilledRegionsMinCount()
		{
			return 0;
		}

		public int ShowFilledRegionsMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetShowFilledRegionsMaxCount()
		{
			return 1;
		}

		public int ShowFilledRegionsMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowFilledRegionsCount()
		{
			return DomChildCount(NodeType.Element, "", "ShowFilledRegions");
		}

		public int ShowFilledRegionsCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "ShowFilledRegions");
			}
		}

		public bool HasShowFilledRegions()
		{
			return HasDomChild(NodeType.Element, "", "ShowFilledRegions");
		}

		public SchemaBoolean GetShowFilledRegionsAt(int index)
		{
			return new SchemaBoolean(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "ShowFilledRegions", index)));
		}

		public XmlNode GetStartingShowFilledRegionsCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "ShowFilledRegions" );
		}

		public XmlNode GetAdvancedShowFilledRegionsCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "ShowFilledRegions", curNode );
		}

		public SchemaBoolean GetShowFilledRegionsValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaBoolean( curNode.InnerText );
		}


		public SchemaBoolean GetShowFilledRegions()
		{
			return GetShowFilledRegionsAt(0);
		}

		public SchemaBoolean ShowFilledRegions
		{
			get
			{
				return GetShowFilledRegionsAt(0);
			}
		}

		public void RemoveShowFilledRegionsAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "ShowFilledRegions", index);
		}

		public void RemoveShowFilledRegions()
		{
			while (HasShowFilledRegions())
				RemoveShowFilledRegionsAt(0);
		}

		public void AddShowFilledRegions(SchemaBoolean newValue)
		{
			AppendDomChild(NodeType.Element, "", "ShowFilledRegions", newValue.ToString());
		}

		public void InsertShowFilledRegionsAt(SchemaBoolean newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "ShowFilledRegions", index, newValue.ToString());
		}

		public void ReplaceShowFilledRegionsAt(SchemaBoolean newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "ShowFilledRegions", index, newValue.ToString());
		}
		#endregion // ShowFilledRegions accessor methods

		#region ShowFilledRegions collection
        public ShowFilledRegionsCollection	MyShowFilledRegionss = new ShowFilledRegionsCollection( );

        public class ShowFilledRegionsCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public ShowFilledRegionsEnumerator GetEnumerator() 
			{
				return new ShowFilledRegionsEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class ShowFilledRegionsEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public ShowFilledRegionsEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.ShowFilledRegionsCount );
			}
			public SchemaBoolean  Current 
			{
				get 
				{
					return(parent.GetShowFilledRegionsAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // ShowFilledRegions collection

		#region ScalarKey accessor methods
		public int GetScalarKeyMinCount()
		{
			return 0;
		}

		public int ScalarKeyMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetScalarKeyMaxCount()
		{
			return 1;
		}

		public int ScalarKeyMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetScalarKeyCount()
		{
			return DomChildCount(NodeType.Element, "", "ScalarKey");
		}

		public int ScalarKeyCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "ScalarKey");
			}
		}

		public bool HasScalarKey()
		{
			return HasDomChild(NodeType.Element, "", "ScalarKey");
		}

		public SchemaString GetScalarKeyAt(int index)
		{
			return new SchemaString(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "ScalarKey", index)));
		}

		public XmlNode GetStartingScalarKeyCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "ScalarKey" );
		}

		public XmlNode GetAdvancedScalarKeyCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "ScalarKey", curNode );
		}

		public SchemaString GetScalarKeyValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaString( curNode.InnerText );
		}


		public SchemaString GetScalarKey()
		{
			return GetScalarKeyAt(0);
		}

		public SchemaString ScalarKey
		{
			get
			{
				return GetScalarKeyAt(0);
			}
		}

		public void RemoveScalarKeyAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "ScalarKey", index);
		}

		public void RemoveScalarKey()
		{
			while (HasScalarKey())
				RemoveScalarKeyAt(0);
		}

		public void AddScalarKey(SchemaString newValue)
		{
			AppendDomChild(NodeType.Element, "", "ScalarKey", newValue.ToString());
		}

		public void InsertScalarKeyAt(SchemaString newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "ScalarKey", index, newValue.ToString());
		}

		public void ReplaceScalarKeyAt(SchemaString newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "ScalarKey", index, newValue.ToString());
		}
		#endregion // ScalarKey accessor methods

		#region ScalarKey collection
        public ScalarKeyCollection	MyScalarKeys = new ScalarKeyCollection( );

        public class ScalarKeyCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public ScalarKeyEnumerator GetEnumerator() 
			{
				return new ScalarKeyEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class ScalarKeyEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public ScalarKeyEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.ScalarKeyCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(parent.GetScalarKeyAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // ScalarKey collection

		#region ShowScalarValues accessor methods
		public int GetShowScalarValuesMinCount()
		{
			return 0;
		}

		public int ShowScalarValuesMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetShowScalarValuesMaxCount()
		{
			return 1;
		}

		public int ShowScalarValuesMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowScalarValuesCount()
		{
			return DomChildCount(NodeType.Element, "", "ShowScalarValues");
		}

		public int ShowScalarValuesCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "ShowScalarValues");
			}
		}

		public bool HasShowScalarValues()
		{
			return HasDomChild(NodeType.Element, "", "ShowScalarValues");
		}

		public SchemaBoolean GetShowScalarValuesAt(int index)
		{
			return new SchemaBoolean(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "ShowScalarValues", index)));
		}

		public XmlNode GetStartingShowScalarValuesCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "ShowScalarValues" );
		}

		public XmlNode GetAdvancedShowScalarValuesCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "ShowScalarValues", curNode );
		}

		public SchemaBoolean GetShowScalarValuesValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaBoolean( curNode.InnerText );
		}


		public SchemaBoolean GetShowScalarValues()
		{
			return GetShowScalarValuesAt(0);
		}

		public SchemaBoolean ShowScalarValues
		{
			get
			{
				return GetShowScalarValuesAt(0);
			}
		}

		public void RemoveShowScalarValuesAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "ShowScalarValues", index);
		}

		public void RemoveShowScalarValues()
		{
			while (HasShowScalarValues())
				RemoveShowScalarValuesAt(0);
		}

		public void AddShowScalarValues(SchemaBoolean newValue)
		{
			AppendDomChild(NodeType.Element, "", "ShowScalarValues", newValue.ToString());
		}

		public void InsertShowScalarValuesAt(SchemaBoolean newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "ShowScalarValues", index, newValue.ToString());
		}

		public void ReplaceShowScalarValuesAt(SchemaBoolean newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "ShowScalarValues", index, newValue.ToString());
		}
		#endregion // ShowScalarValues accessor methods

		#region ShowScalarValues collection
        public ShowScalarValuesCollection	MyShowScalarValuess = new ShowScalarValuesCollection( );

        public class ShowScalarValuesCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public ShowScalarValuesEnumerator GetEnumerator() 
			{
				return new ShowScalarValuesEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class ShowScalarValuesEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public ShowScalarValuesEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.ShowScalarValuesCount );
			}
			public SchemaBoolean  Current 
			{
				get 
				{
					return(parent.GetShowScalarValuesAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // ShowScalarValues collection

		#region DisplayFont accessor methods
		public int GetDisplayFontMinCount()
		{
			return 0;
		}

		public int DisplayFontMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetDisplayFontMaxCount()
		{
			return 1;
		}

		public int DisplayFontMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetDisplayFontCount()
		{
			return DomChildCount(NodeType.Element, "", "DisplayFont");
		}

		public int DisplayFontCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "DisplayFont");
			}
		}

		public bool HasDisplayFont()
		{
			return HasDomChild(NodeType.Element, "", "DisplayFont");
		}

		public Type_DisplayFont2 GetDisplayFontAt(int index)
		{
			return new Type_DisplayFont2(GetDomChildAt(NodeType.Element, "", "DisplayFont", index));
		}

		public XmlNode GetStartingDisplayFontCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "DisplayFont" );
		}

		public XmlNode GetAdvancedDisplayFontCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "DisplayFont", curNode );
		}

		public Type_DisplayFont2 GetDisplayFontValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new Type_DisplayFont2( curNode );
		}


		public Type_DisplayFont2 GetDisplayFont()
		{
			return GetDisplayFontAt(0);
		}

		public Type_DisplayFont2 DisplayFont
		{
			get
			{
				return GetDisplayFontAt(0);
			}
		}

		public void RemoveDisplayFontAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "DisplayFont", index);
		}

		public void RemoveDisplayFont()
		{
			while (HasDisplayFont())
				RemoveDisplayFontAt(0);
		}

		public void AddDisplayFont(Type_DisplayFont2 newValue)
		{
			AppendDomElement("", "DisplayFont", newValue);
		}

		public void InsertDisplayFontAt(Type_DisplayFont2 newValue, int index)
		{
			InsertDomElementAt("", "DisplayFont", index, newValue);
		}

		public void ReplaceDisplayFontAt(Type_DisplayFont2 newValue, int index)
		{
			ReplaceDomElementAt("", "DisplayFont", index, newValue);
		}
		#endregion // DisplayFont accessor methods

		#region DisplayFont collection
        public DisplayFontCollection	MyDisplayFonts = new DisplayFontCollection( );

        public class DisplayFontCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public DisplayFontEnumerator GetEnumerator() 
			{
				return new DisplayFontEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class DisplayFontEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public DisplayFontEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.DisplayFontCount );
			}
			public Type_DisplayFont2  Current 
			{
				get 
				{
					return(parent.GetDisplayFontAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // DisplayFont collection

		#region RGBColor accessor methods
		public int GetRGBColorMinCount()
		{
			return 0;
		}

		public int RGBColorMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetRGBColorMaxCount()
		{
			return 1;
		}

		public int RGBColorMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetRGBColorCount()
		{
			return DomChildCount(NodeType.Element, "", "RGBColor");
		}

		public int RGBColorCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "RGBColor");
			}
		}

		public bool HasRGBColor()
		{
			return HasDomChild(NodeType.Element, "", "RGBColor");
		}

		public Type_RGBColor2 GetRGBColorAt(int index)
		{
			return new Type_RGBColor2(GetDomChildAt(NodeType.Element, "", "RGBColor", index));
		}

		public XmlNode GetStartingRGBColorCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "RGBColor" );
		}

		public XmlNode GetAdvancedRGBColorCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "RGBColor", curNode );
		}

		public Type_RGBColor2 GetRGBColorValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new Type_RGBColor2( curNode );
		}


		public Type_RGBColor2 GetRGBColor()
		{
			return GetRGBColorAt(0);
		}

		public Type_RGBColor2 RGBColor
		{
			get
			{
				return GetRGBColorAt(0);
			}
		}

		public void RemoveRGBColorAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "RGBColor", index);
		}

		public void RemoveRGBColor()
		{
			while (HasRGBColor())
				RemoveRGBColorAt(0);
		}

		public void AddRGBColor(Type_RGBColor2 newValue)
		{
			AppendDomElement("", "RGBColor", newValue);
		}

		public void InsertRGBColorAt(Type_RGBColor2 newValue, int index)
		{
			InsertDomElementAt("", "RGBColor", index, newValue);
		}

		public void ReplaceRGBColorAt(Type_RGBColor2 newValue, int index)
		{
			ReplaceDomElementAt("", "RGBColor", index, newValue);
		}
		#endregion // RGBColor accessor methods

		#region RGBColor collection
        public RGBColorCollection	MyRGBColors = new RGBColorCollection( );

        public class RGBColorCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public RGBColorEnumerator GetEnumerator() 
			{
				return new RGBColorEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class RGBColorEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public RGBColorEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.RGBColorCount );
			}
			public Type_RGBColor2  Current 
			{
				get 
				{
					return(parent.GetRGBColorAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // RGBColor collection

		#region WinColorName accessor methods
		public int GetWinColorNameMinCount()
		{
			return 0;
		}

		public int WinColorNameMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetWinColorNameMaxCount()
		{
			return 1;
		}

		public int WinColorNameMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetWinColorNameCount()
		{
			return DomChildCount(NodeType.Element, "", "WinColorName");
		}

		public int WinColorNameCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "WinColorName");
			}
		}

		public bool HasWinColorName()
		{
			return HasDomChild(NodeType.Element, "", "WinColorName");
		}

		public SchemaString GetWinColorNameAt(int index)
		{
			return new SchemaString(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "WinColorName", index)));
		}

		public XmlNode GetStartingWinColorNameCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "WinColorName" );
		}

		public XmlNode GetAdvancedWinColorNameCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "WinColorName", curNode );
		}

		public SchemaString GetWinColorNameValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaString( curNode.InnerText );
		}


		public SchemaString GetWinColorName()
		{
			return GetWinColorNameAt(0);
		}

		public SchemaString WinColorName
		{
			get
			{
				return GetWinColorNameAt(0);
			}
		}

		public void RemoveWinColorNameAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "WinColorName", index);
		}

		public void RemoveWinColorName()
		{
			while (HasWinColorName())
				RemoveWinColorNameAt(0);
		}

		public void AddWinColorName(SchemaString newValue)
		{
			AppendDomChild(NodeType.Element, "", "WinColorName", newValue.ToString());
		}

		public void InsertWinColorNameAt(SchemaString newValue, int index)
		{
			InsertDomChildAt(NodeType.Element, "", "WinColorName", index, newValue.ToString());
		}

		public void ReplaceWinColorNameAt(SchemaString newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "WinColorName", index, newValue.ToString());
		}
		#endregion // WinColorName accessor methods

		#region WinColorName collection
        public WinColorNameCollection	MyWinColorNames = new WinColorNameCollection( );

        public class WinColorNameCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public WinColorNameEnumerator GetEnumerator() 
			{
				return new WinColorNameEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class WinColorNameEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public WinColorNameEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.WinColorNameCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(parent.GetWinColorNameAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // WinColorName collection

		#region ExtendedInformation accessor methods
		public int GetExtendedInformationMinCount()
		{
			return 0;
		}

		public int ExtendedInformationMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetExtendedInformationMaxCount()
		{
			return 1;
		}

		public int ExtendedInformationMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetExtendedInformationCount()
		{
			return DomChildCount(NodeType.Element, "", "ExtendedInformation");
		}

		public int ExtendedInformationCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "ExtendedInformation");
			}
		}

		public bool HasExtendedInformation()
		{
			return HasDomChild(NodeType.Element, "", "ExtendedInformation");
		}

		public Type_ExtendedInformation GetExtendedInformationAt(int index)
		{
			return new Type_ExtendedInformation(GetDomChildAt(NodeType.Element, "", "ExtendedInformation", index));
		}

		public XmlNode GetStartingExtendedInformationCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "ExtendedInformation" );
		}

		public XmlNode GetAdvancedExtendedInformationCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "ExtendedInformation", curNode );
		}

		public Type_ExtendedInformation GetExtendedInformationValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new Type_ExtendedInformation( curNode );
		}


		public Type_ExtendedInformation GetExtendedInformation()
		{
			return GetExtendedInformationAt(0);
		}

		public Type_ExtendedInformation ExtendedInformation
		{
			get
			{
				return GetExtendedInformationAt(0);
			}
		}

		public void RemoveExtendedInformationAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "ExtendedInformation", index);
		}

		public void RemoveExtendedInformation()
		{
			while (HasExtendedInformation())
				RemoveExtendedInformationAt(0);
		}

		public void AddExtendedInformation(Type_ExtendedInformation newValue)
		{
			AppendDomElement("", "ExtendedInformation", newValue);
		}

		public void InsertExtendedInformationAt(Type_ExtendedInformation newValue, int index)
		{
			InsertDomElementAt("", "ExtendedInformation", index, newValue);
		}

		public void ReplaceExtendedInformationAt(Type_ExtendedInformation newValue, int index)
		{
			ReplaceDomElementAt("", "ExtendedInformation", index, newValue);
		}
		#endregion // ExtendedInformation accessor methods

		#region ExtendedInformation collection
        public ExtendedInformationCollection	MyExtendedInformations = new ExtendedInformationCollection( );

        public class ExtendedInformationCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
					parent = value;
				}
			}
			public ExtendedInformationEnumerator GetEnumerator() 
			{
				return new ExtendedInformationEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class ExtendedInformationEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public ExtendedInformationEnumerator(Type_ShapeFileLayer par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.ExtendedInformationCount );
			}
			public Type_ExtendedInformation  Current 
			{
				get 
				{
					return(parent.GetExtendedInformationAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // ExtendedInformation collection

        private void SetCollectionParents()
        {
            MyShowAtStartups.Parent = this; 
            MyNames.Parent = this; 
            MyDistanceAboveSurfaces.Parent = this; 
            MyMasterFilePaths.Parent = this; 
            MyMinimumViewAltitudes.Parent = this; 
            MyMaximumViewAltitudes.Parent = this; 
            MyShowPointss.Parent = this; 
            MyShowBoundariess.Parent = this; 
            MyShowFilledRegionss.Parent = this; 
            MyScalarKeys.Parent = this; 
            MyShowScalarValuess.Parent = this; 
            MyDisplayFonts.Parent = this; 
            MyRGBColors.Parent = this; 
            MyWinColorNames.Parent = this; 
            MyExtendedInformations.Parent = this; 
	}
}
}
