//
// WorldXmlDescriptorDoc.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;

namespace WorldXmlDescriptor
{
	public class WorldXmlDescriptorDoc : Altova.Xml.Document
	{
		override protected void DeclareNamespaces(Altova.Xml.Node node)
		{
		}
	}
}
