//
// ExtendedCapabilitiesType.cs.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using System.Collections;
using System.Xml;
using Altova.Types;

namespace capabilities_1_3_0.wms
{
	public class ExtendedCapabilitiesType : Altova.Xml.Node
	{
		#region Forward constructors
		public ExtendedCapabilitiesType() : base() { SetCollectionParents(); }
		public ExtendedCapabilitiesType(XmlDocument doc) : base(doc) { SetCollectionParents(); }
		public ExtendedCapabilitiesType(XmlNode node) : base(node) { SetCollectionParents(); }
		public ExtendedCapabilitiesType(Altova.Xml.Node node) : base(node) { SetCollectionParents(); }
		#endregion // Forward constructors

		public override void AdjustPrefix()
		{
		}


        private void SetCollectionParents()
        {
	}
}
}
