//
// showType.cs.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace capabilities_1_3_0.xlink
{

	public class showType : SchemaString
	{
		public showType() : base()
		{
		}

		public showType(string newValue) : base(newValue)
		{
			Validate();
		}

		public new void Validate()
		{
		}
	}
}
